services:
  pg:
    build:
        context: ../.
        dockerfile: ./build/docker/postgres/Dockerfile
    container_name: ticket-pg
    ports:
      - 5432:5432
    volumes:
      - ../build/database/schema/init.sql:/docker-entrypoint-initdb.d/init.sql